### ISSUE TITLE
Market Research

### ISSUE THREAD

**Issue by Essnah12** [flyxiv/ffxiv_simbot#22]
Demographic Analysis
===========

Average Age of RPG Users
------------------------

Characteristic of Millennial
------------------------

Most Popular RPG Games (Active Users)
------------------------
Rank | Name | Subscriber | Daily User of API
--|--|--|--
1 | World of Warcraft | 142,947,748 | Over 500,000 
5 | Final Fantasy | 17,582,601 | 
17 | Lost Ark | 15,673,751 | 
26 | Maplestory | 6,660,364 | 
47 | Dungeon and Fighters | 1,683,958 | 

*Source:  https://activeplayer.io/final-fantasy-xiv/, https://mmo-population.com/r/wow, 

* Find the actual percentage of users using Open API Sites

Actual Usage of Open API in Other Games
---------------------
Rank | Name | Description
--|--|--
1 | Final Fantasy | FFLogs.com, Etro.gg (Gear Slot)
2 | World of Warcraft | Raidbots.com, Warcraftlogs.com, Raider.io
3 | Lost Ark | Loawa.com
4 | Maplestory | ?
5 | Dungeon and Fighters | Dundam.xyz, Dfmax.xyz

Comparison
----------------------------
Rank | Name | Description
--|--|--
1 | Final Fantasy | Only FFlogs, Simulations are unintuitive and inconvenient 
2 | World of Warcraft | Uses the most open api sources: Raids, Milestones, Simulations
3 | Lost Ark | .
4 | Maplestory | Since the update of in-game "Combat Power," Users no longer use terestial sites
5 | Dungeon and Fighters | Recently Neople declared the problems of External-API Sites, claming that they will reduce the effects by providing In-game milestones.

**Comment by Essnah12** [comment]
Oh, that's looks way better thanks

**Comment by Essnah12** [comment]
Can't find the data about how many people use external websites when playing RPG Games

Looking through Google and Reddit but can't see the approximate numbers either

Have to dig further more

**Comment by Essnah12** [comment]
![image](https://github.com/flyxiv/ffxiv_simbot/assets/171755242/2ab9e4d2-7baa-4206-8997-642802f19251)
An average of 200,000 user search for dundam in Korea

We can also see from this statistic that most of them use Mobiles instead of PC 
=> The UI must be mobile friendly

**Comment by Essnah12** [comment]
![image](https://github.com/flyxiv/ffxiv_simbot/assets/171755242/7bba1d83-e79f-4ff7-be10-b4f107644db3)

=> Half of warcraftlog users use simbots

**Comment by Essnah12** [comment]
![image](https://github.com/flyxiv/ffxiv_simbot/assets/171755242/4a88232c-545b-4123-8e83-e04fdfc2426d)


Used Google Ads to find the trend of Open sources but doesn't quietly show the exact number

Have to find another way

**Comment by flyxiv** [comment]
> ![image](https://private-user-images.githubusercontent.com/171755242/338615757-7bba1d83-e79f-4ff7-be10-b4f107644db3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxOTA3NjgsIm5iZiI6MTcxODE5MDQ2OCwicGF0aCI6Ii8xNzE3NTUyNDIvMzM4NjE1NzU3LTdiYmExZDgzLWU3OWYtNGZmNy1iZTEwLWI0ZjEwNzY0NGRiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQxMTA3NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03M2Q4NzAyNTQ4MzUyNzdmMDEyZTQ1NmEzOTBkNGExYzI2ODUyZjUyMTlhMWUzMGQ0NzY2ODkyZDEwMWViOGU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ik5F-KVPDpyEyj5o8Ek8JQ6XaaZcSka3UjPvjOeGyO0)
> 
> => Half of warcraftlog users search for simbots
> 
> Source: https://trends.google.com/trends/explore?date=today%205-y&q=raidbots,warcraftlogs&hl=ko

 @Essnah12 둘의 상관관계가 교집합인건가요?  "WCL 쓰는 사람들 중 50%"인지 "Raidbot의 트래픽은 WCL의 50%정도다" 인지

**Comment by Essnah12** [comment]
Add Subtitle in every comment

Highlight important factors for boss

Make them understand at least 10% of the jobs you have done through out your work
