### ISSUE TITLE
Save Previous User Input

### ISSUE THREAD

**Issue by flyxiv** [flyxiv/ffxiv_simbot#30]
This is a simulation of 8 characters, so it is too cumbersome to select all party members/stat configuration every time a user does a simulation. 

**Always save the most recent simulation option and use that as default values.**

**Comment by flyxiv** [comment]
Luckily we can do it using local storage, something I've already learned while doing #29.

**Comment by flyxiv** [comment]
<img width="828" alt="Screenshot 2024-06-11 at 12 00 16 AM" src="https://github.com/flyxiv/ffxiv_simbot/assets/78268298/d5dd9f8f-b54d-4c42-955c-6c7b1655587f">

Finished implementing page. Now just need to connect these to request.

**Comment by Essnah12** [comment]
Is there a way to insert day & night vision?

Some users like dark background rather than white

**Comment by flyxiv** [comment]
<img width="824" alt="Screenshot 2024-06-11 at 10 41 42 PM" src="https://github.com/flyxiv/ffxiv_simbot/assets/78268298/850604b7-5442-4779-b26a-9551fa4d4617">

Finished caching implementation. Now all the settings of the most recent request is saved.

**Comment by flyxiv** [comment]
@Essnah12 I'll add that when I go back to refining the design
