### ISSUE TITLE
Refine App design

### ISSUE THREAD

**Issue by flyxiv** [flyxiv/ffxiv_simbot#34]
![image](https://github.com/flyxiv/ffxiv_simbot/assets/78268298/3883accf-2520-48ba-893a-f63c7f43ba25)

**Comment by flyxiv** [comment]
![image](https://github.com/flyxiv/ffxiv_simbot/assets/78268298/c4940c93-7450-4c58-acf5-7b1a6a5dcde7)

**Comment by flyxiv** [comment]
# Finished Input Page
<img width="761" alt="Screenshot 2024-06-19 at 11 34 51 PM" src="https://github.com/flyxiv/ffxiv_simbot/assets/78268298/4cd4bbb5-400a-40aa-88fa-bb4aa7e4cc2e">

**Comment by junyeopN** [comment]
# Finished Quick Sim App Design
* Why is frontend so hard lol
<img width="735" alt="Screenshot 2024-06-22 at 3 05 54 PM" src="https://github.com/flyxiv/ffxiv_simbot/assets/17741994/12448489-a6ae-46fe-912f-a1bbdfaffe68">
<img width="697" alt="Screenshot 2024-06-22 at 3 05 59 PM" src="https://github.com/flyxiv/ffxiv_simbot/assets/17741994/d15591ce-6d96-42eb-bcca-12728745c1a7">

<img width="751" alt="Screenshot 2024-06-22 at 3 05 50 PM" src="https://github.com/flyxiv/ffxiv_simbot/assets/17741994/98203fb8-ac34-47bd-949e-5df5d5b0a966">

<img width="749" alt="Screenshot 2024-06-22 at 3 05 40 PM" src="https://github.com/flyxiv/ffxiv_simbot/assets/17741994/4b6071bc-9cd6-40e9-b7a0-1f1eca37cb4f">
